name: sdk
channels:
  - memfault
  - conda-forge
  - defaults
dependencies:
  - gcc-arm-none-eabi=10.3.2021.10
  - make=4.3
  - ninja=1.11.0
  - cmake=3.23.3
  - python=3.10.5
  - pip=22.2.1
  - doxygen=1.9.5
  - jq=1.6
  - pip:
    - pyocd==0.34.1
